version: '3'
services:
  mongo:
    image: 'mongo:latest'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - TEST_DATABASE_URL=mongodb://mongo:27017/default
      - SECRET=123abc
      - PORT=4000
      - NODE_ENV=development
    depends_on:
      - mongo
