version: '3'
services:
  mongo:
    image: 'mongo:latest'
  nginx:
    restart: always
    image: 'USERNAME/fullstack-nginx'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - api
      - client
  api:
    image: 'USERNAME/fullstack-server'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/default
      - SECRET=123abc
      - PORT=8000
      - NODE_ENV=production
    depends_on:
      - mongo
  client:
    image: 'USERNAME/fullstack-client'
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    depends_on: 
      - client
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
